# app/config/config.yml
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    default_database: my_database
    document_managers:
        default:
            auto_mapping: true